name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    name: 'Build distribution'
    runs-on: ubuntu-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade build
      - name: Build distribution
        run: |
          python -m build
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  Windows:
    name: 'Windows (${{ matrix.python }}, ${{ matrix.arch }}${{ matrix.extra_name }})'
    timeout-minutes: 20
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
        arch: ['x86', 'x64']
        lsp: ['']
        lsp_extract_file: ['']
        extra_name: ['']
        include:
          - python: '3.10'
            arch: 'x64'
            lsp: 'https://raw.githubusercontent.com/python-trio/trio-ci-assets/master/komodia-based-vpn-setup.zip'
            lsp_extract_file: 'komodia-based-vpn-setup.exe'
            extra_name: ', with Komodia LSP'
          - python: '3.10'
            arch: 'x64'
            lsp: 'https://www.proxifier.com/download/legacy/ProxifierSetup342.exe'
            lsp_extract_file: ''
            extra_name: ', with IFS LSP'
          - python: '3.10'  # <- not actually used
            arch: 'x64'
            pypy_nightly_branch: 'py3.10'
            extra_name: ', pypy 3.10 nightly'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python }}'
          architecture: '${{ matrix.arch }}'
          cache: pip
          cache-dependency-path: test-requirements.txt
      - name: Run tests
        run: ./ci.sh
        shell: bash
        env:
          LSP: '${{ matrix.lsp }}'
          LSP_EXTRACT_FILE: '${{ matrix.lsp_extract_file }}'
          # Should match 'name:' up above
          JOB_NAME: 'Windows (${{ matrix.python }}, ${{ matrix.arch }}${{ matrix.extra_name }})'

  Ubuntu:
    name: 'Ubuntu (${{ matrix.python }}${{ matrix.extra_name }})'
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['pypy-3.9', 'pypy-3.10', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14-dev']
        check_formatting: ['0']
        pypy_nightly_branch: ['']
        extra_name: ['']
        include:
          - python: '3.10'
            check_formatting: '1'
            extra_name: ', check formatting'
          - python: '3.9'  # <- not actually used
            pypy_nightly_branch: 'py3.9'
            extra_name: ', pypy 3.9 nightly'
          - python: '3.10'  # <- not actually used
            pypy_nightly_branch: 'py3.10'
            extra_name: ', pypy 3.10 nightly'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        if: "!endsWith(matrix.python, '-dev')"
        with:
          python-version: '${{ matrix.python }}'
          cache: pip
          cache-dependency-path: test-requirements.txt
      - name: Setup python (dev)
        uses: deadsnakes/action@v3.1.0
        if: endsWith(matrix.python, '-dev')
        with:
          python-version: '${{ matrix.python }}'
      - name: Run tests
        run: ./ci.sh
        env:
          PYPY_NIGHTLY_BRANCH: '${{ matrix.pypy_nightly_branch }}'
          CHECK_FORMATTING: '${{ matrix.check_formatting }}'
          # Should match 'name:' up above
          JOB_NAME: 'Ubuntu (${{ matrix.python }}${{ matrix.extra_name }})'

  macOS:
    name: 'macOS (${{ matrix.python }})${{ matrix.extra_name }}'
    timeout-minutes: 10
    runs-on: 'macos-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
        extra_name: ['']
        include:
          - python: '3.10'  # <- not actually used
            arch: 'x64'
            pypy_nightly_branch: 'py3.10'
            extra_name: ', pypy 3.10 nightly'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python }}'
          cache: pip
          cache-dependency-path: test-requirements.txt
      - name: Run tests
        run: ./ci.sh
        env:
          PYPY_NIGHTLY_BRANCH: '${{ matrix.pypy_nightly_branch }}'
          # Should match 'name:' up above
          JOB_NAME: 'macOS (${{ matrix.python }})${{ matrix.extra_name }}'

  Alpine:
    name: 'Alpine'
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    container: 'python:3-alpine'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: ./ci.sh
        env:
          # Should match 'name:' up above
          JOB_NAME: 'Alpine'

  no-test-requirements:
    name: "Ubuntu (3.x, no test requirements)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      run: |
        python -m pytest -xvs trio/_tests/test_imports.py::test_core_is_properly_reexported
        python -c "import trio.testing; print('trio.testing import ok')"

  no-cython-tests:
    name: "Ubuntu (3.x, compiled without Cython)"
    runs-on: ubuntu-latest
    env:
      TRIO_DISABLE_CYTHON: "1"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      run: |
        python -c "import trio; print(trio.lowlevel.current_task())"

  coverage:
    name: 'Ubuntu (3.x, coverage)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip
          cache-dependency-path: test-requirements.txt
      - name: Run tests
        run: ./ci.sh
        env:
          # Should match 'name:' up above
          JOB_NAME: 'Ubuntu (3.x, coverage)'
          COVERAGE: '1'